baseURL = 'https://0xalibabas.github.io/'
languageCode = 'en-us'
title = '0x_alibabas'
theme = 'PaperMod'

[params]
  env = 'production'
  description = 'Red Team security research, penetration testing, and offensive security insights'
  keywords = ['red team', 'penetration testing', 'cybersecurity', 'offensive security', 'hacking']
  author = '0x_alibabas'
  
  # Analytics disabled
  googleAnalytics = ''
  
  # Theme settings
  defaultTheme = 'dark'
  disableThemeToggle = false
  
  # Assets
  [params.assets]
    favicon = 'images/favicon/favicon.ico'
    favicon16x16 = 'images/favicon/favicon-16x16.png'
    favicon32x32 = 'images/favicon/favicon-32x32.png'
  
  # Header label logo (shown next to site title)
  [params.label]
    text = '0x_alibabas'
    icon = 'images/favicon/favicon-32x32.png'
    iconHeight = 30
  
  # Social links
  [params.social]
    GitHub = 'https://github.com/0xalibabas'
    Twitter = ''
    LinkedIn = ''
    
  # Menu
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
    
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 20
    
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Sitemap configuration
[sitemap]
  changefreq = 'monthly'
  priority = 0.5
  filename = 'sitemap.xml'

# Output formats
[outputs]
  home = ['HTML', 'RSS', 'JSON']

# Taxonomies
[taxonomies]
  tag = 'tags'
  category = 'categories'

# Build settings
[build]
  writeStats = true
